repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
      exclude: "(mkdocs.yml|recipe/meta.yaml)"
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    - id: mypy
      additional_dependencies: ['types-requests']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
  - repo: https://github.com/akaihola/darker
    rev: 1.7.2
    hooks:
      - id: darker
        additional_dependencies: [black==22.10.0]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
