name: conda-auth-docs
channels:
  - conda-forge
dependencies:
  - conda-sphinx-theme==0.1.3
  - linkify-it-py==2.0.0
  - myst-parser=0.18.1
  - sphinx-copybutton=0.5.0
  - sphinx-design=0.5.0
  - sphinx-sitemap=2.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-mermaid=0.7.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
