name: conda-auth tests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/tests.yml"
      - "conda_auth/**"
      - "pixi.lock"
      - "pixi.toml"
      - "pyproject.toml"
      - "recipe/**"
      - "tests/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/tests.yml"
      - "conda_auth/**"
      - "pixi.lock"
      - "pixi.toml"
      - "pyproject.toml"
      - "recipe/**"
      - "tests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.draft == false

    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-minor: ["10", "11", "12", "13", "14"]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.70.2
          environments: dev-py3${{ matrix.python-minor }}

      - name: Run test and generate coverage
        run: pixi run -e dev-py3${{ matrix.python-minor }} testcov

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-minor == '13'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          fail_ci_if_error: ${{ github.event_name != 'pull_request' }}
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    name: Integration tests
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.70.2
          environments: dev-py312

      - name: Install local package
        run: pixi run -e dev-py312 develop

      - name: Run integration tests
        run: pixi run -e dev-py312 test-integration

  build:
    name: Canary Build
    needs: [tests, integration-tests]
    # only build canary build if
    # - prior steps succeeded,
    # - this is the main branch
    if: >-
      success()
      && !github.event.repository.fork
      && github.ref_name == 'main'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            subdir: noarch
    env:
      CONDA_SOLVER: classic
    runs-on: ${{ matrix.runner }}
    steps:
      # Clean checkout of specific git ref needed for package metadata version
      # which needs env vars GIT_DESCRIBE_TAG and GIT_BUILD_STR:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      # TODO: If this is ever promoted to conda, we should upload to "conda-canary" organization instead
      - name: Create and upload canary build
        uses: conda/actions/canary-release@7f6830b1428a9bd47f0b068892c77eae95207037 # v26.1.0
        with:
          package-name: ${{ github.event.repository.name }}
          subdir: ${{ matrix.subdir }}
          anaconda-org-channel: thath
          anaconda-org-label: ${{ github.ref_name == 'main' && 'dev' || format('{0}-{1}', github.event.repository.name, github.ref_name) }}
          anaconda-org-token: ${{ secrets.ANACONDA_ORG_TOKEN }}
          conda-build-arguments: '--override-channels -c defaults'
