name: conda-auth tests

on:
  push:
    branches:
      - main
    paths:
      - "conda_auth/**"
      - "tests/**"
      - "*.py"
      - "recipe/**"
      - ".github/workflows/tests.yml"
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "conda_auth/**"
      - "tests/**"
      - "*.py"
      - "recipe/**"
      - ".github/workflows/tests.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.draft == false

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        test-env: ["dev-py38", "dev-py39", "dev-py310", "dev-py311", "dev-py312"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.70.2
          environments: ${{ matrix.test-env }}

      - name: Run test and generate coverage
        run: pixi run --environment ${{matrix.test-env}} testcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          flags: ${{ runner.os }},${{ matrix.test-env }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Canary Build
    needs: [tests]
    # only build canary build if
    # - prior steps succeeded,
    # - this is the main branch
    if: >-
      success()
      && !github.event.repository.fork
      && github.ref_name == 'main'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            subdir: noarch
    env:
      CONDA_SOLVER: classic
    runs-on: ${{ matrix.runner }}
    steps:
      # Clean checkout of specific git ref needed for package metadata version
      # which needs env vars GIT_DESCRIBE_TAG and GIT_BUILD_STR:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      # TODO: If this is ever promoted to conda, we should upload to "conda-canary" organization instead
      - name: Create and upload canary build
        uses: conda/actions/canary-release@7f6830b1428a9bd47f0b068892c77eae95207037 # v26.1.0
        with:
          package-name: ${{ github.event.repository.name }}
          subdir: ${{ matrix.subdir }}
          anaconda-org-channel: thath
          anaconda-org-label: ${{ github.ref_name == 'main' && 'dev' || format('{0}-{1}', github.event.repository.name, github.ref_name) }}
          anaconda-org-token: ${{ secrets.ANACONDA_ORG_TOKEN }}
          conda-build-arguments: '--override-channels -c defaults'
